"""add shifts absences

Revision ID: 6511f37c20ab
Revises: 6ebe257886da
Create Date: 2026-02-26 03:30:50.409237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6511f37c20ab'
down_revision: Union[str, None] = '6ebe257886da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'day', name='uq_absences_advisor_day')
    )
    op.create_index(op.f('ix_absences_advisor_id'), 'absences', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_absences_day'), 'absences', ['day'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_minute > 0 AND end_minute <= 1440', name='ck_shifts_end_minute_range'),
    sa.CheckConstraint('end_minute > start_minute', name='ck_shifts_end_gt_start'),
    sa.CheckConstraint('start_minute >= 0 AND start_minute < 1440', name='ck_shifts_start_minute_range'),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'day', name='uq_shifts_advisor_day')
    )
    op.create_index(op.f('ix_shifts_advisor_id'), 'shifts', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_shifts_day'), 'shifts', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_day'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_advisor_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_absences_day'), table_name='absences')
    op.drop_index(op.f('ix_absences_advisor_id'), table_name='absences')
    op.drop_table('absences')
    # ### end Alembic commands ###
