"""add breaks table

Revision ID: f9433cf8449c
Revises: 5d1de69ec295
Create Date: 2026-03-04 02:58:37.634534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9433cf8449c'
down_revision: Union[str, None] = '5d1de69ec295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_minute', sa.SmallInteger(), nullable=False),
    sa.Column('end_minute', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='auto', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'day', 'start_minute', name='uq_breaks_advisor_day_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breaks')
    # ### end Alembic commands ###
